age = 20
print(age)
print(type(age))

price = 99.99
print(price)
print(type(price))

name = "Shreya"
print(name)
print(type(name))

is_student = True
print(is_student)
print(type(is_student))

fruits = ["Apple", "Banana", "Mango"]
print(fruits)
print(type(fruits))

colors = ("Red", "Green", "Blue")
print(colors)
print(type(colors))

numbers = {1, 2, 3, 4}
print(numbers)
print(type(numbers))

student = {
    "name": "Shreya",
    "age": 20,
    "course": "BCA"
}

print(student)
print(type(student))
